// Approved R20-R22 archive/results presentation with injected public data.
import {archiveKind as kind} from '../data.js?v=20261007v2pages9';
import {renderResultTabs,renderRaceConditions,installResultTabs} from '/src/shared/race-result-context.js?v=20261010results1';
export function createArchiveViews(api) {
  const {raw,state,tx,label,section,metric,num,delta,route,trackName,trackCode,safeTrack,pageDriver,raceRating,raceBestLapId,time,carMarkup,eloCategory,eloNumber,viewer}=api;
  const title=screen=>screen==='archive'?tx('Архив гонок','Race archive'):tx('Результаты гонки','Race results');
  function crumb(screen,extra='') {return `<div class="page-breadcrumb"><a href="${route()}">${tx('Главная','Home')}</a><span>/</span><b>${title(screen)}</b>${extra}<span class="page-snapshot">${raw.archive?.generated_at?tx('Обновлено','Updated')+' · '+time(raw.archive.generated_at):''}</span></div>`;}
  function intro(name,description,action='',image=null) {return `<section class="panel site-intro${image?' has-image':''}"${image?` style="--site-cover:url('${label(image)}')"`:''}><div><span class="eyebrow">ASG RACING</span><h1>${label(name)}</h1><p>${description}</p></div><div class="site-intro-actions">${action}</div></section>`;}
  function seo(screen,description) {return `<section class="panel page-seo"><h2>${title(screen)} · ASG Racing ACC</h2><p>${description}</p></section>`;}
  function table(headers,rows,css='') {return `<div class="page-table-scroll"><table class="page-table ${css}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;}
  function badge(r) {const k=kind(r);return `<span class="event-kind kind-${k}">${k==='championship'?tx('Чемпионат','Championship'):k==='endurance'?tx('Эндюранс','Endurance'):k==='monoclass'?tx('Монокласс','Single model'):k==='hourly'?tx('Часовая гонка','Hourly race'):tx('Публичная гонка','Public race')}</span>`;}
  function paginate() {const a=raw.archive;return `<div class="page-pagination"><span>${a.total_items?((a.page-1)*10+1):0}–${Math.min(a.page*10,a.total_items)} / ${num(a.total_items)}</span><button type="button" data-site-step="archive" data-step="-1" aria-label="${tx('Предыдущая страница','Previous page')}"${a.page<=1?' disabled':''}>‹</button><b>${a.page} / ${a.total_pages}</b><button type="button" data-site-step="archive" data-step="1" aria-label="${tx('Следующая страница','Next page')}"${a.page>=a.total_pages?' disabled':''}>›</button></div>`;}
  function archiveContent() {
    const rows=raw.archive.items.map(r=>`<tr tabindex="0" role="button" data-page-race="${label(r.race_id)}" aria-label="${tx('Результаты','Results')}: ${label(trackName(trackCode(r)))}"><td>${time(r.finished_at)}</td><td><div class="site-track-cell"><img src="/assets/${safeTrack(r)}.jpg" alt=""><b>${label(trackName(trackCode(r)))}</b><span class="archive-server" title="${label(r.server_name || r.source)}">· ${label(r.server_name || r.source)}</span></div></td><td>${badge(r)}</td><td><div class="archive-inline">${pageDriver({public_id:r.winner_public_id,driver:r.winner})}<span class="archive-car">· ${carMarkup(r.winner_car_name,r.winner_car_model_id)}</span></div></td><td>${num(r.participants_count)}</td><td><span class="rating-badge elo-${eloCategory({elo:r.average_elo})}">${eloNumber(r.average_elo)}</span></td><td><div class="archive-inline"><b class="best-lap-value">${label(r.best_lap)}</b>${pageDriver({public_id:r.best_lap_public_id,driver:r.best_lap_driver})}</div></td><td><a class="text-link" href="${route('race',r.race_id)}" aria-label="${tx('Страница результатов','Result page')}">↗</a></td></tr>`).join('');
    return (rows?table([tx('Дата · UTC+3','Date · UTC+3'),tx('Трасса / сервер','Circuit / server'),tx('Формат','Format'),tx('Победитель','Winner'),tx('Пилоты','Drivers'),'ELO',tx('Лучший круг','Best lap'),''],rows,'archive-table'):`<p class="site-empty">${tx('По выбранным условиям ничего не найдено.','Nothing matches these filters.')}</p>`)+paginate();
  }
  function archiveView() {
    return crumb('archive')+intro(title('archive'),tx('Результаты серверов ASG Racing. Выбери гонку, открой протокол и перейди к пилоту.','ASG Racing server results. Choose a race, open its result sheet and visit a driver.'),`<a class="button" href="${route('hourly')}">${tx('Ближайшие старты','Upcoming races')} ↗</a>`)+section(tx('Результаты','Results'),`<div class="site-tools"><label class="page-search"><span aria-hidden="true">⌕</span><input type="search" id="site-archive-search" value="${label(state.archiveQuery)}" placeholder="${tx('Трасса, сервер, победитель','Circuit, server, winner')}" aria-label="${tx('Трасса, сервер, победитель','Circuit, server, winner')}"></label><label>${tx('Трасса','Circuit')}<select id="site-archive-track"><option value="">${tx('Все трассы','All circuits')}</option>${raw.archiveTracks.map(c=>`<option value="${label(c)}"${c===state.archiveTrack?' selected':''}>${label(trackName(c))}</option>`).join('')}</select></label><label>${tx('Формат','Format')}<select id="site-archive-kind"><option value="">${tx('Все форматы','All formats')}</option>${['public','hourly','monoclass','endurance','championship'].map(k=>`<option value="${k}"${k===state.archiveKind?' selected':''}>${k==='public'?tx('Публичные','Public'):k==='hourly'?tx('Часовые','Hourly'):k==='monoclass'?tx('Монокласс','Single model'):k==='endurance'?tx('Эндюранс','Endurance'):tx('Чемпионат','Championship')}</option>`).join('')}</select></label><label>${tx('Порядок','Order')}<select id="site-archive-order"><option value="desc"${state.archiveOrder==='desc'?' selected':''}>${tx('Сначала новые','Newest first')}</option><option value="asc"${state.archiveOrder==='asc'?' selected':''}>${tx('Сначала старые','Oldest first')}</option></select></label></div><div id="site-archive-content">${archiveContent()}</div><p class="page-help" id="archive-status" role="status"></p>`)+seo('archive',tx('Архив гонок Assetto Corsa Competizione: трассы, результаты, победители, лучшие круги и сила стартовой решётки.','Assetto Corsa Competizione race archive: circuits, results, winners, fastest laps and grid strength.'));
  }
  function raceView(r) {
    installResultTabs();
    const current=viewer(),rows=r.results.map(d=>`<tr${d.position>=1&&d.position<=3?` data-podium-place="${d.position}"`:''}${current.authenticated&&current.publicId===d.public_id?' class="current-user-row" aria-current="true"':''}><td><b>${num(d.position)}</b></td><td>${num(d.start_position)}</td><td>${delta(d.positions_delta)}</td><td><span class="result-driver-identity"><small>#${label(d.race_number)}</small>${pageDriver(d)}</span></td><td>${carMarkup(d.car_name,d.car_model_id)}</td><td><b class="${d.public_id&&d.public_id===raceBestLapId(r)?'best-lap-value':'personal-lap-value'}">${label(d.best_lap)}</b></td><td>${label(d.gap)}</td><td>${raceRating(d,'elo')}</td><td>${delta(d.elo_rating_delta)}</td><td>${raceRating(d,'sr')}</td><td>${num(d.points)}</td></tr>`).join('');
    return crumb('race',`<a href="${route('archive')}">← ${title('archive')}</a>`)+intro(trackName(trackCode(r)),`${time(r.finished_at)} · ${badge(r)}`,`<button class="button" type="button" data-page-race="${label(r.race_id)}">${tx('Открыть в модалке','Open modal')} ↗</button>`,'/assets/'+safeTrack(r)+'.jpg')+section(tx('Итоги заезда','Race summary'),`<div class="site-summary">${metric(tx('Пилоты','Drivers'),num(r.participants_count))}${metric(tx('Победитель','Winner'),pageDriver({public_id:r.winner_public_id,driver:r.winner}))}${metric(tx('Лучший круг','Best lap'),`<span class="best-lap-value">${label(r.best_lap)}</span>`,pageDriver({public_id:r.best_lap_public_id,driver:r.best_lap_driver}))}${metric(tx('Средний ELO','Average ELO'),eloNumber(r.average_elo))}</div>`)+section(tx('Результаты гонки','Race results'),renderResultTabs(r,table(['#',tx('Старт','Grid'),'±',tx('Пилот','Driver'),tx('Машина','Car'),tx('Лучший круг','Best lap'),tx('Отставание','Gap'),'ELO','Δ ELO','SR',tx('Очки','Points')],rows,'results-table'),api,'page-results'),renderRaceConditions(r,api))+seo('race',tx('Полный результат гонки ACC с позициями, машинами, лучшими кругами и изменениями рейтинга.','Full ACC race results with positions, cars, best laps and rating changes.'));
  }
  return {archiveView,archiveContent,raceView};
}
