// Approved R20 news/article/community layout with existing public data/actions.
import {prepareNews,localizedEditorial,editorialImage,editorialHref} from '../editorial-model.js?v=20261007v2pages10';
import {sortCommunityPosts} from '/src/pages/community/feed-model.js';
import {renderCommunityTextBlocks} from '/src/pages/community/post-view.js';
import {getCommunityPostKey} from '/src/pages/community/feed-model.js';
import {loadNewsReadState} from '/news-read-state.js';
import {formatMoscowDate} from '/src/shared/time.js';
export function createEditorialViews(api){
 const {raw,state,tx,label,section,metric,route,pageDriver,time,language}=api;
 const titles={news:()=>tx('Новости','News'),article:()=>tx('Новость','Article'),community:()=>tx('Сообщество','Community'),catalog:()=>tx('Клубы и команды','Clubs & teams'),instructions:()=>tx('Как играть','How to join'),championship:()=>tx('Чемпионат','Championship')};
 const empty=(message=tx('По выбранным условиям ничего не найдено.','Nothing matches these filters.'))=>`<p class="site-empty">${message}</p>`;
 const intro=(title,description,action='')=>`<section class="panel site-intro"><div><span class="eyebrow">ASG RACING</span><h1>${label(title)}</h1><p>${description}</p></div><div class="site-intro-actions">${action}</div></section>`;
 const crumb=(screen,extra='')=>`<div class="page-breadcrumb"><a href="${route()}">${tx('Главная','Home')}</a><span>/</span><b>${titles[screen]()}</b>${extra}<span class="page-snapshot">${tx('Обновлено','Updated')} · ${time(raw.editorialUpdated)}</span></div>`;
 const seo=(screen,text)=>`<section class="panel page-seo"><h2>${titles[screen]()} · ASG Racing ACC</h2><p>${text}</p></section>`;
 const tools=html=>`<div class="site-tools">${html}</div>`;
 const search=(id,value,text)=>`<label class="page-search"><span aria-hidden="true">⌕</span><input type="search" id="${id}" value="${label(value)}" placeholder="${text}" aria-label="${text}"></label>`;
 const table=(heads,rows,css='')=>`<div class="page-table-scroll"><table class="page-table ${css}"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
 const paginate=(name,page,total,size)=>{const max=Math.max(1,Math.ceil(total/size));return `<div class="page-pagination"><span>${total?(page-1)*size+1:0}–${Math.min(page*size,total)} / ${total}</span><button type="button" data-site-step="${name}" data-step="-1" aria-label="${tx('Предыдущая страница','Previous page')}"${page<=1?' disabled':''}>‹</button><b>${page} / ${max}</b><button type="button" data-site-step="${name}" data-step="1" aria-label="${tx('Следующая страница','Next page')}"${page>=max?' disabled':''}>›</button></div>`;};

 const news=()=>prepareNews(raw.news,language);
 const isRead=id=>{try{return Boolean(loadNewsReadState(localStorage)[id]);}catch{return false;}};
 const postDate=value=>formatMoscowDate(value,language==='ru'?'ru-RU':'en-GB',{year:'numeric'})||'—';
 function newsBody(item){return item.body.map(block=>{
   if(typeof block==='string')return `<p>${label(block)}</p>`;
   if(block?.type==='list')return `<ul>${block.items.map(t=>`<li>${label(t)}</li>`).join('')}</ul>`;
   if(block?.type==='link'){const href=editorialHref(block.href,language,route);return href?`<p><a class="button" href="${label(href)}"${new URL(href,location.origin).hash==='#rules'?' data-modal="rules"':''} rel="noopener noreferrer">${label(block.label)} ↗</a></p>`:`<p>${label(block.label)}</p>`;}
   return '';
 }).join('');}
 function reaction(id){const s=raw.likes?.states[id]||{loading:true};return `<div class="site-post-actions" data-reaction="${label(id)}"><button class="button" type="button" data-site-like="${label(id)}" aria-pressed="${Boolean(s.already_liked)}"${raw.likes?.readonly||s.loading||s.failed||s.already_liked?' disabled':''}>${s.already_liked?'♥':'♡'} ${s.already_liked?tx('Уже нравится','Liked'):tx('Нравится','Like')} · ${s.loading?'…':s.failed?'—':s.likes??'—'}</button><small role="status">${s.failed?`${tx('Лайки недоступны','Likes unavailable')} <button class="text-link" type="button" data-likes-retry>${tx('Повторить','Retry')}</button>`:`${raw.likes?.readonly?tx('Лайки доступны на основном домене.','Likes are available on the main domain.'):tx('Для реакций используется ID браузера.','Reactions use a browser ID.')} <a href="${route('document','privacy')}">${tx('Подробнее','Details')}</a>`}</small></div>`;}
  function newsContent() {
   const all=news().filter(n=>(!state.newsKind||n.kind===state.newsKind)&&`${n.title} ${n.summary}`.toLowerCase().includes(state.newsQuery.toLowerCase()));state.newsPage=Math.max(1,Math.min(state.newsPage,Math.ceil(all.length/6)||1));
   return (all.length?`<div class="site-news-grid">${all.slice((state.newsPage-1)*6,state.newsPage*6).map(n=>`<article class="site-news-card">${n.thumbnail_url?`<a class="site-news-cover" href="${route('article',n.slug)}"><img src="${label(n.thumbnail_url)}" alt="${label(n.image_alt || '')}" loading="lazy"></a>`:''}<div><div class="site-news-meta"><time>${time(n.published_at)}</time><span>${n.is_pinned?tx('Закреплено','Pinned'):label(n.kind || '')}</span></div><h2><a href="${route('article',n.slug)}">${label(n.title)}</a></h2><p>${label(n.summary)}</p><a class="text-link" href="${route('article',n.slug)}">${isRead(n.id)?tx('Прочитано','Read'):tx('Читать','Read more')} ↗</a></div></article>`).join('')}</div>`:empty())+paginate('news',state.newsPage,all.length,6);
  }
  function newsView() {return crumb('news')+intro(titles.news(),tx('Изменения проекта, анонсы и информация для пилотов.','Project updates, announcements and driver information.'))+section(tx('Лента','Feed'),tools(search('site-news-search',state.newsQuery,tx('Поиск новости','Search news'))+`<label>${tx('Тип','Type')}<select id="site-news-kind"><option value="">${tx('Все новости','All news')}</option>${[...new Set(news().map(n=>n.kind))].map(k=>`<option value="${label(k)}"${state.newsKind===k?' selected':''}>${k==='announcement'?tx('Анонсы','Announcements'):k==='update'?tx('Обновления','Updates'):label(k)}</option>`).join('')}</select></label>`)+`<div id="site-news-content">${newsContent()}</div>`)+seo('news',tx('Новости ASG Racing: анонсы гонок, изменения рейтингов и развитие сообщества ACC.','ASG Racing news: race announcements, rating updates and ACC community development.'));}
  function articleView(id) {
   const n=news().find(n=>n.id===id||n.slug===id);if(!n)return api.missing('article',id);
   return crumb('article',`<a href="${route('news')}">← ${titles.news()}</a>`)+intro(n.title,`${time(n.published_at)} · ${tx('Прочитано','Read')}`)+`<article class="panel site-reader site-article">${n.cover_image_url?`<img class="site-article-cover" src="${label(n.cover_image_url)}" alt="${label(n.image_alt || '')}">`:''}${newsBody(n)}<a class="button" href="${route('news')}">← ${tx('Ко всем новостям','All news')}</a></article>`+seo('article',label(n.summary));
  }
  function communityContent() {
   const posts=sortCommunityPosts(raw.community);state.communityPage=Math.max(1,Math.min(state.communityPage,Math.ceil(posts.length/3)||1));const all=posts.slice((state.communityPage-1)*3,state.communityPage*3);
   return `<div class="site-community-feed">${all.map(p=>`<article class="site-post"><div class="site-post-meta"><span class="eyebrow">ASG RACING</span><time>${postDate(p.date)}</time></div><h2>${label(localizedEditorial(p.title,language))}</h2>${renderCommunityTextBlocks(localizedEditorial(p.text,language),{escapeHtml:label})}<div class="site-post-gallery">${(p.images || []).filter(img=>editorialImage(img?.src,'https://asgracing.ru/community/')).slice(0,2).map((img,i)=>`<button type="button" data-site-image="${label(getCommunityPostKey(p))}" data-image-index="${i}" aria-label="${tx('Открыть изображение','Open image')}"><img src="${label(editorialImage(img?.src,'https://asgracing.ru/community/'))}" alt="${label(localizedEditorial(img.alt,language))}" loading="lazy"></button>`).join('')}</div>${reaction(getCommunityPostKey(p))}</article>`).join('')||empty(tx('Публикаций пока нет.','No posts yet.'))}</div>`+paginate('community',state.communityPage,posts.length,3);
  }
  function communityView() {return crumb('community')+intro(titles.community(),tx('Новости жизни ASG Racing, итоги чемпионатов и встречи на трассе.','Life at ASG Racing, championship recaps and racing together.'),`<a class="button" href="https://t.me/+JUymrENgddcyMTdi" target="_blank" rel="noopener">Telegram ↗</a><a class="button" href="https://discord.gg/cEPFHXXtTC" target="_blank" rel="noopener">Discord ↗</a>`)+`<div class="site-community-layout">${section(tx('Жизнь проекта','Community feed'),`<div id="site-community-content">${communityContent()}</div>`)}<aside class="panel site-community-aside"><h2>${tx('Будь частью гонки','Be part of the race')}</h2><p>${tx('Найди клуб, подготовься к первому старту и следи за результатами.','Find a club, prepare for your first start and follow the results.')}</p>${['catalog','instructions','championship','news'].map(k=>`<a class="button" href="${route(k)}">${titles[k]()} ↗</a>`).join('')}<button class="button" type="button" data-about-nav>${tx('О сервере','About the server')} ↗</button></aside></div>`+seo('community',tx('Сообщество ASG Racing в Assetto Corsa Competizione: пилоты, события, чемпионаты и общение.','ASG Racing Assetto Corsa Competizione community: drivers, events, championships and conversation.'));}
 return {newsView,newsContent,articleView,communityView,communityContent,reaction,news};
}
