// Approved R20 club/team layout with validated public snapshot data.
import {filterCatalogEntries} from '/src/pages/clubs-teams/catalog-model.js';
export function createEntityViews(api) {
 const {raw,state,tx,label,section,metric,num,decimal,route,pageDriver,raceRating,trackName,time,eloCategory,eloNumber,viewer}=api;
 const data={entities:raw.entities,rankings:raw.club_rankings,entity_details:raw.entity_details};
 const titles={catalog:()=>tx('Клубы и команды','Clubs & teams'),club:()=>tx('Клуб','Club'),team:()=>tx('Команда','Team')};
 const empty=(message=tx('По выбранным условиям ничего не найдено.','Nothing matches these filters.'))=>`<p class="site-empty">${message}</p>`;
 const table=(heads,rows)=>`<div class="page-table-scroll"><table class="page-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
 const tools=html=>`<div class="site-tools">${html}</div>`;
 const search=(id,value,text)=>`<label class="page-search"><span aria-hidden="true">⌕</span><input type="search" id="${id}" value="${label(value)}" placeholder="${text}" aria-label="${text}"></label>`;
 const crumb=(screen,extra='')=>`<div class="page-breadcrumb"><a href="${route()}">${tx('Главная','Home')}</a><span>/</span><b>${titles[screen]()}</b>${extra}<span class="page-snapshot">${tx('Обновлено','Updated')} · ${time(raw.entitiesUpdated)}</span></div>`;
 const intro=(title,description)=>`<section class="panel site-intro"><div><span class="eyebrow">ASG RACING</span><h1>${label(title)}</h1><p>${description}</p></div><div class="site-intro-actions"></div></section>`;
 const seo=(screen,description)=>`<section class="panel page-seo"><h2>${titles[screen]()} · ASG Racing ACC</h2><p>${description}</p></section>`;
 const safeHref=url=>url;
  function entityHref(entity,type) {return route(type,entity.slug);}
  function entityLogo(e) {return e.local_asset?`<img class="site-entity-logo" src="${label(e.local_asset)}" alt="">`:`<span class="site-entity-logo fallback" aria-hidden="true">${label(e.display_name?.slice(0,2))}</span>`;}
  function catalogContent() {
   if(raw.catalogError)return empty(tx('Не удалось загрузить этот зачёт.','Could not load this ranking.'))+`<button class="button" type="button" data-catalog-retry>${tx('Повторить','Retry')}</button>`;
   if(raw.catalogLoading)return empty(tx('Загрузка рейтинга…','Loading ranking…'));
   const entities=data.entities[state.catalogType] || [],rankings=data.rankings?.[state.catalogContext]?.[state.catalogType] || raw.club_rankings[state.catalogContext]?.[state.catalogType] || [];
   const all=filterCatalogEntries(entities,state.catalogQuery).map(e=>({...e,...(state.catalogContext==='general'?{}:{position:null,total_points:null,race_count:null,average_elo:null,average_sr:null}),...rankings.find(r=>r.slug===e.slug),local_asset:e.local_asset})).sort((a,b)=>(a.position ?? 999)-(b.position ?? 999));
   return all.length?`<div class="site-catalog-grid">${all.map(e=>`<article class="site-entity-card"><div class="site-entity-heading">${entityLogo(e)}<div><span class="eyebrow">${state.catalogType==='clubs'?tx('Клуб','Club'):tx('Команда','Team')}</span><h2><a href="${entityHref(e,state.catalogType==='clubs'?'club':'team')}">${label(e.display_name)}</a></h2>${e.club?`<span>${tx('Клуб','Club')}: <a href="${entityHref(e.club,'club')}">${label(e.club.display_name)}</a></span>`:''}</div><b>#${e.position ?? '—'}</b></div><div class="site-entity-stats"><span><b>${num(e.total_points)}</b>${tx('очков','points')}</span><span><b>${num(e.members_count)}</b>${tx('пилотов','drivers')}</span><span><b><span class="rating-badge elo-${eloCategory({elo:e.average_elo})}">${eloNumber(e.average_elo)}</span></b>ELO</span><span><b><span class="rating-badge sr sr-${e.average_sr>=5?'a':e.average_sr>=2.5?'b':'c'}">${decimal(e.average_sr)}</span></b>SR</span></div><a class="button" href="${entityHref(e,state.catalogType==='clubs'?'club':'team')}">${tx('Состав и результаты','Roster & results')} ↗</a></article>`).join('')}</div>`:empty();
  }
  function catalogView() {return crumb('catalog')+intro(titles.catalog(),tx('Сообщества, составы и общий результат на серверах ASG Racing.','Communities, rosters and collective results on ASG Racing servers.'))+section(tx('Каталог и рейтинг','Catalog & ranking'),tools(`<div class="club-switch" role="group" aria-label="${titles.catalog()}">${['clubs','teams'].map(k=>`<button type="button" class="button" data-site-catalog="${k}" aria-pressed="${state.catalogType===k}">${k==='clubs'?tx('Клубы','Clubs'):tx('Команды','Teams')}</button>`).join('')}</div>`+search('site-catalog-search',state.catalogQuery,tx('Название клуба или команды','Club or team name'))+`<label>${tx('Зачёт','Ranking')}<select id="site-catalog-context">${['general','hourly','championship'].map(k=>`<option value="${k}"${k===state.catalogContext?' selected':''}>${k==='general'?tx('Общий','General'):k==='hourly'?tx('Часовые гонки','Hourly races'):tx('Чемпионат','Championship')}</option>`).join('')}</select></label>`)+`<div id="site-catalog-content">${catalogContent()}</div>`)+seo('catalog',tx('Каталог клубов и команд ASG Racing: составы пилотов, рейтинг, очки, ELO и Safety Rating.','ASG Racing club and team catalog: driver rosters, rankings, points, ELO and Safety Rating.'));}
  function rosterContent(entity) {
   const list=(entity.roster || []).filter(d=>d.display_name.toLowerCase().includes(state.rosterQuery.toLowerCase()));
   return list.length?table([tx('Пилот','Driver'),tx('Роль','Role'),'ELO','SR'],list.map(d=>`<tr${viewer().authenticated&&d.public_id===viewer().publicId?' class="current-user-row"':''}><td>${pageDriver({...d,driver:d.display_name})}</td><td>${d.role==='head'?tx('Руководитель','Head'):d.role==='captain'?tx('Капитан','Captain'):tx('Участник','Member')}</td><td>${raceRating({...d,driver:d.display_name},'elo')}</td><td>${raceRating({...d,driver:d.display_name},'sr')}</td></tr>`).join('')):empty();
  }
  function entityView(type,id) {
   const e=data.entity_details[(type==='club'?'clubs/':'teams/')+id];if(!e)return crumb(type)+empty(tx('Клуб или команда не найдены.','Club or team not found.'));
   const r=e.rating || {}, recent=(e.recent_races || []);
   return crumb(type,`<a href="${route('catalog')}">← ${titles.catalog()}</a>`)+`<section class="panel site-entity-hero">${entityLogo(e)}<div><span class="eyebrow">${titles[type]()}</span><h1>${label(e.display_name)}</h1><p>${label(e['description_'+api.lang] || e.description_ru || e.description_en || tx('Описание не опубликовано.','No published description.'))}</p>${e.club?`<span>${tx('Клуб','Club')}: <a class="entity-link" href="${entityHref(e.club,'club')}">${label(e.club.display_name)}</a></span>`:''}</div><div class="site-entity-hero-rank"><span>${tx('Место в общем зачёте','General ranking')}</span><b>#${r.position ?? '—'}</b>${e.website_url?`<a href="${label(safeHref(e.website_url))}" target="_blank" rel="noopener">${tx('Сайт','Website')} ↗</a>`:''}</div></section><div class="panel site-summary">${metric(tx('Пилоты','Drivers'),num(r.members_count))}${metric(tx('Очки','Points'),num(r.total_points))}${metric(tx('Гонки','Races'),num(r.race_count))}${metric(tx('Средний ELO','Average ELO'),`<span class="rating-badge elo-${eloCategory({elo:r.average_elo})}">${eloNumber(r.average_elo)}</span>`)}${metric(tx('Средний SR','Average SR'),`<span class="rating-badge sr sr-${r.average_sr>=5?'a':r.average_sr>=2.5?'b':'c'}">${decimal(r.average_sr)}</span>`)}</div><div class="site-detail-grid"><div>${section(tx('Состав','Roster'),tools(search('site-roster-search',state.rosterQuery,tx('Поиск пилота','Search driver')))+`<div id="site-roster-content">${rosterContent(e)}</div>`)}</div><div>${section(tx('Последние командные результаты','Recent collective results'),`<div id="site-entity-races">${recentContent(e)}</div>`)}${e.teams?.length?section(tx('Команды клуба','Club teams'),`<div class="site-linked-list">${e.teams.map(t=>`<a href="${entityHref(t,'team')}">${label(t.display_name)} <span>↗</span></a>`).join('')}</div>`):''}${section(tx('Вступление и управление','Joining & management'),`<div class="site-reader"><p>${tx('Состав клуба и команды управляется через кабинет и портал. Условия вступления определяет руководство.','Club and team rosters are managed through the account and portal. The leadership sets joining requirements.')}</p>${entityActions(e,type)}</div>`)}</div></div>`+seo(type,tx('Профиль сообщества ASG Racing: состав, командные очки, рейтинг и история результатов.','ASG Racing community profile: roster, collective points, rankings and result history.'));
  }
 function entityActions(e,type) {
   const link=(values,text)=>{const query=new URLSearchParams(values);if(api.lang==='ru')query.set('lang','ru');return `<a class="button" href="/account/?${label(query.toString())}">${text} ↗</a>`;};
   return link({membership_type:type,membership_target:e.public_id,membership_name:e.display_name},tx('Подать заявку на вступление','Request membership'))+link({affiliation_action:type==='club'?'request':e.club?'detach':'invite',affiliation_target:e.public_id,affiliation_name:e.display_name},type==='club'?tx('Заявка на привязку команды','Request team affiliation'):e.club?tx('Управление привязкой клуба','Manage club affiliation'):tx('Пригласить команду в мой клуб','Invite team to my club'));
 }
 function recentContent(e) {
   const rows=e.recent_races || [],max=Math.max(1,Math.ceil(rows.length/10));state.entityRacePage=Math.max(1,Math.min(state.entityRacePage,max));
   if(!rows.length)return empty(tx('Зачтённых гонок пока нет.','No counted races yet.'));
   return `<div class="site-linked-list">${rows.slice((state.entityRacePage-1)*10,state.entityRacePage*10).map(r=>`<button type="button" data-page-race="${label(r.race_uid)}"><span><b>${label(trackName(r.track_code))}</b><small>${time(r.race_started_at)}</small></span><span><b>${num(r.points)}</b> ${tx('очков','points')} ↗</span></button>`).join('')}</div><p class="page-help">${tx('Опубликованные результаты зачтённых гонок.','Published results of counted races.')}</p>`+(max>1?`<div class="page-pagination"><span>${(state.entityRacePage-1)*10+1}–${Math.min(state.entityRacePage*10,rows.length)} / ${rows.length}</span><button type="button" data-entity-races-step="-1"${state.entityRacePage===1?' disabled':''}>‹</button><b>${state.entityRacePage} / ${max}</b><button type="button" data-entity-races-step="1"${state.entityRacePage===max?' disabled':''}>›</button></div>`:'');
 }
 return {catalogView,catalogContent,entityView,rosterContent,recentContent};
}
