// Approved R20 championship history cards over published seasons.
export function createHistoryViews(api){
 const {raw,state,tx,label,section,metric,route,pageDriver,time}=api;
 const titles={seasons:()=>tx('История чемпионатов','Championship history')};
 const empty=(message=tx('По выбранным условиям ничего не найдено.','Nothing matches these filters.'))=>`<p class="site-empty">${message}</p>`;
 const intro=(title,description,action='')=>`<section class="panel site-intro"><div><span class="eyebrow">ASG RACING</span><h1>${label(title)}</h1><p>${description}</p></div><div class="site-intro-actions">${action}</div></section>`;
 const crumb=screen=>`<div class="page-breadcrumb"><a href="${route()}">${tx('Главная','Home')}</a><span>/</span><b>${titles[screen]()}</b><span class="page-snapshot">${tx('Обновлено','Updated')} · ${time(raw.editorialUpdated)}</span></div>`;
 const seo=(screen,text)=>`<section class="panel page-seo"><h2>${titles[screen]()} · ASG Racing ACC</h2><p>${text}</p></section>`;
 const tools=html=>`<div class="site-tools">${html}</div>`;
 const search=(id,value,text)=>`<label class="page-search"><span aria-hidden="true">⌕</span><input type="search" id="${id}" value="${label(value)}" placeholder="${text}" aria-label="${text}"></label>`;
 const table=(heads,rows,css='')=>`<div class="page-table-scroll"><table class="page-table ${css}"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
 const paginate=(name,page,total,size)=>{const max=Math.max(1,Math.ceil(total/size));return `<div class="page-pagination"><span>${total?(page-1)*size+1:0}–${Math.min(page*size,total)} / ${total}</span><button type="button" data-site-step="${name}" data-step="-1" aria-label="${tx('Предыдущая страница','Previous page')}"${page<=1?' disabled':''}>‹</button><b>${page} / ${max}</b><button type="button" data-site-step="${name}" data-step="1" aria-label="${tx('Следующая страница','Next page')}"${page>=max?' disabled':''}>›</button></div>`;};

 const status=s=>s.status==='active'?tx('Идёт сезон','Active season'):s.status==='scheduled'?tx('Скоро старт','Starts soon'):tx('Завершён','Finished');
 const filtered=()=>raw.historySeasons.filter(s=>(!state.historyStatus||s.status===state.historyStatus)&&`${s.title} ${s.period}`.toLocaleLowerCase().includes(state.historyQuery.trim().toLocaleLowerCase()));
 function seasonsView(){return crumb('seasons')+intro(titles.seasons(),tx('История этапов, итоговый зачёт и опубликованные сезоны.','Round history, final standings and published seasons.'),`<a class="button" href="${route('championships')}">${tx('Все чемпионаты','All championships')} ↗</a>`)+section(tx('Сезоны','Seasons'),tools(search('site-history-search',state.historyQuery,tx('Название или месяц сезона','Season title or month'))+`<label>${tx('Статус','Status')}<select id="site-history-status"><option value="">${tx('Все','All')}</option>${['scheduled','finished','archived'].map(k=>`<option value="${k}"${state.historyStatus===k?' selected':''}>${status({status:k})}</option>`).join('')}</select></label>`)+`<div id="site-history-content">${historyCards()}</div>`)+seo('seasons',tx('История чемпионатов ASG Racing, чемпионы сезонов и результаты этапов.','ASG Racing championship history, season champions and round results.'));}
 function historyCards(){return filtered().length?`<div class="site-catalog-grid">${filtered().map(s=>`<a class="site-season-card" href="${route('championship',s.slug)}" style="--site-cover:url('/assets/${s.races?.[0]?.track_code || s.upcoming_races?.[0]?.track_code || 'spa'}.jpg')"><span class="event-kind season-status status-${s.status==='scheduled'?'scheduled':s.status==='active'?'active':'finished'}">${status(s)}</span><h2>${label(s.title)}</h2><p>${s.races?.length || 0} ${tx('этапов завершено','rounds completed')} · ${s.standings?.length || 0} ${tx('пилотов','drivers')}</p><b>${s.standings?.[0]?label(s.standings[0].driver):tx('Старт впереди','Starts soon')} ↗</b></a>`).join('')}</div>`:empty(tx('Сезоны не найдены. Измени фильтр.','No seasons found. Change the filter.'));}
 return {seasonsView,historyCards};
}
