// Approved R20 readers/instructions and R24 about/error screens.
export function createInformationViews(api){
 const {tx,label,route,section,language,raw}=api;
 const titles={about:()=>tx('О сообществе','About the community'),instructions:()=>tx('Инструкции','Instructions'),guide:()=>tx('Как участвовать','How to participate'),documents:()=>tx('Документы','Documents'),document:()=>tx('Документ','Document')};
 const crumb=(name,extra='')=>`<div class="page-breadcrumb"><a href="${route()}">${tx('Главная','Home')}</a><span>/</span><b>${titles[name]()}</b>${extra}</div>`;
 const intro=(title,description,actions='',image=null)=>`<section class="panel site-intro${image?' has-image':''}"${image?` style="--site-cover:url('/assets/${image}.jpg')"`:''}><div><span class="eyebrow">ASG RACING</span><h1>${label(title)}</h1><p>${description}</p></div><div class="site-intro-actions">${actions}</div></section>`;
 const seo=(name,text)=>`<section class="panel page-seo"><h2>${titles[name]()} · ASG Racing ACC</h2><p>${text}</p></section>`;
 const documentTitle=id=>id==='privacy'?tx('Политика персональных данных','Personal data policy'):tx('Cookies и аналитика','Cookies and analytics');
 function missing(type='page',id=''){
  const names={page:tx('Страница не найдена','Page not found'),driver:tx('Пилот не найден','Driver not found'),race:tx('Гонка не найдена','Race not found'),championship:tx('Чемпионат не найден','Championship not found'),club:tx('Клуб не найден','Club not found'),team:tx('Команда не найдена','Team not found'),article:tx('Новость не найдена','Article not found'),document:tx('Документ не найден','Document not found'),guide:tx('Инструкция не найдена','Guide not found'),car:tx('Машина не найдена','Car not found')};
  return `<section class="panel r24-error" aria-labelledby="missing-title"><span class="r24-error-code" aria-hidden="true">404</span><span class="eyebrow">ASG RACING</span><h1 id="missing-title">${names[type]||names.page}</h1><p>${tx('По этому адресу нет страницы или опубликованной записи. Возможно, ссылка устарела.','There is no page or published record at this address. The link may be outdated.')}</p>${id?`<code>${label(id)}</code>`:''}<div class="control-actions"><a class="button primary" href="${route()}">${tx('На главную','Go home')}</a><a class="button" href="${route('archive')}">${tx('Архив гонок','Race archive')}</a><a class="button" href="${route('championships')}">${tx('Чемпионаты','Championships')}</a></div></section>`;
 }
 function unavailable(){return `<section class="panel r24-error"><span class="eyebrow">ASG RACING</span><h1>${tx('Данные временно недоступны','Data temporarily unavailable')}</h1><p role="status">${tx('Не удалось загрузить данные. Попробуй ещё раз.','Could not load the data. Please try again.')}</p><div class="control-actions"><button class="button primary" type="button" data-page-retry>${tx('Повторить','Retry')}</button><a class="button" href="${route()}">${tx('На главную','Go home')}</a></div></section>`;}
 function aboutView(){
  const g=raw.information.guides.about[language];
  return crumb('about')+intro(tx('О сообществе ASG Racing','About the ASG Racing community'),label(g.intro),`<a class="button primary" href="${route('instructions')}">${tx('Как начать гонять','How to start racing')} ↗</a>`,'monza')+`<div class="r24-about-layout"><article class="panel site-reader">${g.sections.map((s,i)=>`<section id="about-${i}"><h2>${label(s.title)}</h2>${s.html}</section>`).join('')}</article><aside class="panel r24-reader-links"><h2>${tx('Следующий шаг','Your next steps')}</h2>${[['hourly',tx('Выбрать гонку','Choose a race')],['championships',tx('Чемпионаты','Championships')],['catalog',tx('Клубы и команды','Clubs & teams')],['community',tx('Сообщество','Community')],['documents',tx('Документы','Documents')]].map(([key,title])=>`<a class="button" href="${route(key)}">${title} ↗</a>`).join('')}</aside></div>`+seo('about',label(g.intro));
 }
 function instructionView(){const g=raw.information.guides.join[language];return crumb('instructions')+intro(titles.instructions(),label(g.intro),`<a class="button primary" href="${route('hourly')}">${tx('Выбрать гонку','Choose a race')} ↗</a>`)+section(tx('Первый старт','Your first start'),`<div class="site-instruction-steps">${g.sections.map((s,i)=>`<article><b class="site-step-number">0${i+1}</b><div><h3>${label(s.title)}</h3>${s.html}</div></article>`).join('')}</div>`)+section(tx('Справочник пилота','Driver reference'),`<div class="site-catalog-grid">${[['rules',tx('Гоночные правила','Racing rules'),tx('Поведение на трассе и порядок участия.','Track conduct and participation.')],['elo','ELO',tx('Мастерство и сила соперников.','Skill and strength of rivals.')],['safety','Safety Rating',tx('Безопасность и требования допуска.','Safety and eligibility.')]].map(([key,title,text])=>`<button class="site-reference-card" type="button" data-modal="${key}"><b>${title} ↗</b><span>${text}</span></button>`).join('')}<a class="site-reference-card" href="${route('about')}"><b>${tx('О проекте','About the project')} ↗</b><span>${tx('Гонки, команды и общение.','Races, teams and conversation.')}</span></a><a class="site-reference-card" href="${route('documents')}"><b>${titles.documents()} ↗</b><span>${tx('Персональные данные и cookies.','Personal data and cookies.')}</span></a></div>`)+seo('instructions',tx('Как начать гонять на ASG Racing в ACC, найти сервер, проверить допуск и подготовиться к гонке.','How to race with ASG Racing in ACC, find a server, check eligibility and prepare for a race.'));}
 function guideView(id='join'){const g=raw.information.guides[id||'join']?.[language];if(!g)return missing('guide',id);return crumb('guide',`<a href="${route('instructions')}">← ${titles.instructions()}</a>`)+intro(g.title,label(g.intro))+section(tx('Информация','Information'),`<div class="site-reader">${g.sections.map((s,i)=>`<section id="guide-${i}"><h2>${label(s.title)}</h2>${s.html}</section>`).join('')}<a class="button" href="${route('hourly')}">${tx('Выбрать гонку','Choose a race')} ↗</a><button class="button" type="button" data-modal="rules">${tx('Правила','Rules')} ↗</button></div>`)+seo('guide',label(g.intro));}
 function documentsView(){return crumb('documents')+intro(titles.documents(),tx('Официальные тексты политики персональных данных и использования cookies.','Official personal data and cookie policy documents.'))+`<div class="site-document-grid">${Object.entries(raw.information.documents).map(([id,d])=>`<a class="panel site-document-card" href="${route('document',id)}"><span aria-hidden="true">▤</span><div><h2>${documentTitle(id)}</h2><p>${tx('Официальный текст, навигация по разделам и связанные документы.','Official text, section navigation and related documents.')}</p><small>${d.sections.length} ${tx('разделов','sections')} · ASG Racing ↗</small></div></a>`).join('')}</div>`+section(tx('Правила и рейтинги','Rules and ratings'),`<div class="site-document-actions"><button class="button" type="button" data-modal="rules">${tx('Гоночные правила','Racing rules')} ↗</button><button class="button" type="button" data-modal="elo">ELO ↗</button><button class="button" type="button" data-modal="safety">Safety Rating ↗</button><a class="button" href="${route('instructions')}">${titles.instructions()} ↗</a></div>`)+seo('documents',tx('Документы ASG Racing: обработка персональных данных, cookies, аналитика и правила участия.','ASG Racing documents: personal data processing, cookies, analytics and participation rules.'));}
 function documentView(id){const d=Object.hasOwn(raw.information.documents,id)?raw.information.documents[id]:null;if(!d)return missing('document',id);const note=language==='en'?'<p class="site-document-note">The official document is published in Russian. Its original text and the source’s English note are preserved below.</p>':'';return crumb('document',`<a href="${route('documents')}">← ${titles.documents()}</a>`)+intro(documentTitle(id),tx('Оригинальный текст документа ASG Racing.','Original ASG Racing document text.'))+`<div class="site-document-layout"><aside class="panel site-document-toc"><h2>${tx('Содержание','Contents')}</h2>${d.sections.map(s=>`<a href="#document-${s.id}" data-site-scroll>${label(s.title==='Введение'?tx('Введение','Introduction'):s.title)}</a>`).join('')}</aside><article class="panel site-reader site-document-reader" data-document="${label(id)}">${note}${d.intro_html}${d.sections.map(s=>`<section id="document-${s.id}"><h2>${label(s.title==='Введение'?tx('Введение','Introduction'):s.title)}</h2>${s.html}</section>`).join('')}</article></div>`+seo('document',documentTitle(id)+' · ASG Racing');}
 return {aboutView,instructionView,guideView,documentsView,documentView,missing,unavailable};
}
