// Approved results layout; only the official fastest lap is highlighted.
import {decorateRaceHeading, renderResultTabs, installResultTabs} from '/src/shared/race-result-context.js?v=20261010results1';
export function paintRace(r,api) {
 installResultTabs();
 decorateRaceHeading(document.getElementById('v2-modal-title'), r, api);
 const {fixture,tx,label,detail,time,eloNumber,pageDriver,raceRating,raceBestLapId,delta,num,carMarkup,viewer}=api;
 const rows=r.results || [];
      const bestId=r.best_lap_public_id || fixture.recent.find(item=>item.race_id===r.race_id)?.best_lap_public_id || rows.find(d=>d.driver===r.best_lap_driver)?.public_id;
      const bestDriver=rows.find(d=>d.public_id===bestId);
      const bestName=bestDriver?.driver || r.best_lap_driver || fixture.recent.find(item=>item.race_id===r.race_id)?.best_lap_driver;
      const attribution=bestId&&bestName?`<small class="best-lap-driver">${pageDriver({public_id:bestId,driver:bestName})}</small>`:'';
      const summary=`<div class="detail-grid race-summary-grid">${detail(tx('Дата / время','Date / time'),time(r.finished_at))}${detail(tx('Участники','Participants'),r.participants_count??rows.length)}${detail(tx('Победитель','Winner'),r.winner || '—')}<div><span>${tx('Лучший круг','Best lap')}</span><b class="${r.partial?'personal-lap-value':'best-lap-value'}">${label(r.best_lap)}</b>${attribution}</div>${detail(tx('Средний ELO','Average ELO'),eloNumber(r.average_elo))}</div>`;
      const headers=['Финиш|Finish','Старт|Start','± поз.|± pos.','Пилот|Driver','Лучший круг|Best lap','Машина|Car','Отставание|Gap','ELO|ELO','Δ ELO|Δ ELO','SR|SR','Очки|Points'];
      document.getElementById('v2-modal-body').innerHTML=summary+`<div class="page-table-scroll"><table class="page-table results-table"><thead><tr>${headers.map(h=>`<th>${tx(...h.split('|'))}</th>`).join('')}</tr></thead><tbody>${rows.map(d=>`<tr${Number.isInteger(Number(d.position))&&Number(d.position)>=1&&Number(d.position)<=3?` data-podium-place="${Number(d.position)}"`:""}${d.public_id===viewer.publicId&&viewer.authenticated?' class="current-user-row" aria-current="true"':''}><td><b>${d.position??'—'}</b></td><td>${d.start_position??'—'}</td><td>${delta(d.positions_delta)}</td><td><div class="result-driver"><span class="result-driver-identity"><small>#${d.race_number??'—'}</small>${pageDriver(d)}</span></div></td><td><span class="${d.public_id&&d.public_id===raceBestLapId(r)?'best-lap-value':'personal-lap-value'}">${label(d.best_lap)}</span></td><td>${carMarkup(d.car_name,d.car_model_id)}${d.counted_for_stats===false?`<small class="uncounted">${tx('Не зачтено','Not counted')}</small>`:''}</td><td>${label(d.gap)}</td><td>${raceRating(d,'elo')}</td><td>${delta(d.elo_rating_delta)}</td><td>${raceRating(d,'sr')}</td><td>${num(d.points)}</td></tr>`).join('')}</tbody></table></div><p class="page-help">${r.partial?tx('В снимок включён личный результат этого пилота. Полный протокол этой гонки ещё не добавлен.','This snapshot includes the driver’s result. The full result sheet for this race has not been added yet.'):tx('Имена открывают профили; ELO и SR — историю рейтинга.','Names open profiles; ELO and SR open rating history.')}</p>`;
 document.getElementById('v2-modal-body').innerHTML=renderResultTabs(r,document.getElementById('v2-modal-body').innerHTML,api,'modal-results');
}
