// Approved R20 bans presentation; ten rows and verified public profile links.
export function createBansViews(api) {
 const {raw,state,tx,label,section,metric,route,pageDriver,time}=api;
 const titles={bans:()=>tx('Баны','Bans')};
 const empty=()=>`<p class="site-empty">${tx('По выбранным условиям ничего не найдено.','Nothing matches these filters.')}</p>`;
 const intro=(title,description,action='')=>`<section class="panel site-intro"><div><span class="eyebrow">ASG RACING</span><h1>${label(title)}</h1><p>${description}</p></div><div class="site-intro-actions">${action}</div></section>`;
 const crumb=screen=>`<div class="page-breadcrumb"><a href="${route()}">${tx('Главная','Home')}</a><span>/</span><b>${titles[screen]()}</b><span class="page-snapshot">${tx('Обновлено','Updated')} · ${time(raw.bans.generated_at)}</span></div>`;
 const seo=(screen,text)=>`<section class="panel page-seo"><h2>${titles[screen]()} · ASG Racing ACC</h2><p>${text}</p></section>`;
 const tools=html=>`<div class="site-tools">${html}</div>`;
 const search=(id,value,text)=>`<label class="page-search"><span aria-hidden="true">⌕</span><input type="search" id="${id}" value="${label(value)}" placeholder="${text}" aria-label="${text}"></label>`;
 const table=(heads,rows,css='')=>`<div class="page-table-scroll"><table class="page-table ${css}"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
 const paginate=(name,page,total,size)=>{const max=Math.max(1,Math.ceil(total/size));return `<div class="page-pagination"><span>${total?(page-1)*size+1:0}–${Math.min(page*size,total)} / ${total}</span><button type="button" data-site-step="${name}" data-step="-1" aria-label="${tx('Предыдущая страница','Previous page')}"${page<=1?' disabled':''}>‹</button><b>${page} / ${max}</b><button type="button" data-site-step="${name}" data-step="1" aria-label="${tx('Следующая страница','Next page')}"${page>=max?' disabled':''}>›</button></div>`;};
  function bansContent() {const all=raw.bans.items.filter(b=>b.name.toLocaleLowerCase().includes(state.bansQuery.trim().toLocaleLowerCase()));state.bansPage=Math.max(1,Math.min(state.bansPage,Math.ceil(all.length/10)||1));return (all.length?table([tx('Пилот','Driver'),tx('Дата блокировки · UTC+3','Banned at · UTC+3'),tx('Статус','Status')],all.slice((state.bansPage-1)*10,state.bansPage*10).map(b=>`<tr><td>${b.public_id?pageDriver({...b,driver:b.name}):`<span title="${tx('Профиль не определён однозначно','Profile cannot be uniquely identified')}">${label(b.name)}</span>`}</td><td>${time(b.banned_at)}</td><td><span class="banned-badge">${tx('ЗАБАНЕН','BANNED')}</span></td></tr>`).join(''),'bans-table'):empty())+paginate('bans',state.bansPage,all.length,10);}
  function bansView() {return crumb('bans')+intro(titles.bans(),tx('Опубликованный список блокировок на серверах проекта.','Published bans on the project servers.'),`<button class="button" type="button" data-modal="rules">${tx('Правила','Rules')} ↗</button>`)+`<div class="panel site-summary">${metric(tx('В списке','Listed bans'),raw.bans.items.length)}${metric(tx('Последняя блокировка','Latest ban'),time(raw.bans.items[0]?.banned_at))}</div>`+section(tx('Блокировки','Bans'),tools(search('site-bans-search',state.bansQuery,tx('Имя пилота','Driver name')))+`<div id="site-bans-content">${bansContent()}</div><p class="page-help">${tx('В публичном источнике доступны имя и дата. Причины и сроки не опубликованы.','The public source provides names and dates. Reasons and durations are not published.')}</p>`)+seo('bans',tx('Публичный список блокировок ASG Racing и ссылки на правила поведения в гонках ACC.','ASG Racing public ban list and ACC racing conduct rules.'));}
 return {bansView,bansContent};
}
