// Approved R24 fun-statistics presentation; complete public period summaries.
export function createFunViews(api) {
 const {raw,state,tx,label,section,metric,num,decimal,route,pageDriver,time}=api;
 const titles={fun:()=>tx('Фан-статистика','Fun statistics')};
 const empty=message=>`<section class="panel page-panel"><p class="site-empty">${message}</p></section>`;
 const intro=(title,description,actions='')=>`<section class="panel site-intro"><div><span class="eyebrow">ASG RACING</span><h1>${label(title)}</h1><p>${description}</p></div><div class="site-intro-actions">${actions}</div></section>`;
 const crumb=screen=>`<div class="page-breadcrumb"><a href="${route()}">${tx('Главная','Home')}</a><span>/</span><b>${titles[screen]()}</b><span class="page-snapshot">${tx('Обновлено','Updated')} · ${time(raw.fun.generated_at)}</span></div>`;
 const seo=(title,text)=>`<section class="panel page-seo"><h2>${title} · ASG Racing ACC</h2><p>${text}</p></section>`;
 const linkDriver=d=>/^drv_[a-z0-9]+$/i.test(d?.publicId||d?.public_id||'')?pageDriver({...d,public_id:d.publicId||d.public_id}):label(d?.driver);
 const carLink=c=>{const u=new URL(route('cars'),location.origin);u.searchParams.set('car',c.car_name||c.car||c);return `<a href="${label(u.pathname+u.search)}">${label(c.car_name||c.car||c)}</a>`;};
  function funContent(){
   const f=raw.fun[state.period];if(!f)return empty(tx('Сводка за этот период пока не опубликована.','The summary for this period has not been published yet.'));const a=f.awards||{},s=f.summary||{};
   const awards=[['pointsBoss',tx('Король очков','Points boss'),'points',tx('очков','points'),'gold'],['grindKing',tx('Марафонец','Grind king'),'starts',tx('стартов','starts'),'cyan'],['podiumHunter',tx('Охотник за подиумами','Podium hunter'),'podiums',tx('подиумов','podiums'),'gold'],['comebackHero',tx('Прорыв периода','Comeback hero'),'positionsGain',tx('отыгранных позиций','positions gained'),'cyan'],['cleanOperator',tx('Чистая работа','Clean operator'),'penaltyPoints',tx('штрафных баллов','penalty points'),'green'],['hotLapHero',tx('Герой быстрого круга','Hot lap hero'),'lap',tx('лучший круг','best lap'),'purple'],['chaosMagnet',tx('Магнит хаоса','Chaos magnet'),'penaltyPoints',tx('штрафных баллов','penalty points'),'red'],['garageFavorite',tx('Любимец гаража','Garage favorite'),'starts',tx('стартов','starts'),'cyan']];
   const lists=[['active',tx('Самые активные','Most active'),'starts',tx('стартов','starts')],['movers',tx('Прорывы','Position gains'),'positionsGain',tx('позиций','positions')],['clean',tx('Самые чистые','Cleanest drivers'),'penaltyPoints',tx('штрафных баллов','penalty points')],['stable',tx('Стабильность','Consistency'),'averageFinish',tx('средний финиш','average finish')],['fastest',tx('Быстрые круги','Fastest laps'),'fastestLapAwards',tx('наград','awards')],['cars',tx('Популярные машины','Popular cars'),'starts',tx('стартов','starts')]];
   return `<div class="r24-fun-range">${tx('Период','Period')}: ${time(f.range_start)} — ${time(f.range_end)}</div><div class="panel site-summary">${metric(tx('Гонки','Races'),num(s.races))}${metric(tx('Активные пилоты','Active drivers'),num(s.activeDrivers))}${metric(tx('Отвоёванные позиции','Positions gained'),num(s.overtakes))}${metric(tx('Лидер быстрых кругов','Fastest lap leader'),linkDriver(s.fastestLapLeader),`${num(s.fastestLapLeader?.fastestLapAwards)} ${tx('наград','awards')}`)}</div><div class="r24-award-grid">${awards.filter(([key])=>a[key]).map(([key,title,value,unit,color])=>`<article class="panel r24-award accent-${color}"><span class="eyebrow">${title}</span><h2>${key==='garageFavorite'?carLink(a[key]):linkDriver(a[key])}</h2><b class="${key==='hotLapHero'?'best-lap-value':''}">${typeof a[key][value]==='number'?num(a[key][value]):label(a[key][value])}</b><span>${unit}${key==='cleanOperator'?` · ${num(a[key].starts)} ${tx('стартов','starts')}`:''}</span></article>`).join('')}</div><div class="r24-fun-lists">${lists.map(([key,title,value,unit])=>section(title,`<ol class="r24-stat-list">${(Array.isArray(f.lists?.[key])?f.lists[key]:[]).map((d,i)=>`<li><span>${i+1}</span><div>${key==='cars'?carLink(d):linkDriver(d)}</div><b>${value==='averageFinish'?decimal(d[value]):num(d[value])}<small>${unit}</small></b></li>`).join('') || `<li>${tx('Данных за период пока нет.','No data for this period yet.')}</li>`}</ol>`)).join('')}</div>`;
  }
  function funView(){return crumb('fun')+intro(titles.fun(),tx('Кто чаще стартует, прорывается вперёд и собирает подиумы.','Who races most, gains positions and collects podiums.'),`<a class="button" href="${route('cars')}">${tx('Статистика машин','Car statistics')} ↗</a>`)+`<div class="panel r24-period-tabs"><div class="club-switch">${['week','month'].map(k=>`<button type="button" class="button" data-r24-period="${k}" aria-pressed="${state.period===k}">${k==='week'?tx('Неделя','Week'):tx('Месяц','Month')}</button>`).join('')}</div><span>${tx('Полные опубликованные сводки за период','Complete published summaries for the period')}</span></div><div id="r24-fun-content">${funContent()}</div>`+seo(titles.fun(),tx('Фан-статистика ASG Racing: лидеры недели и месяца, активность пилотов, подиумы, чистота и популярные машины.','ASG Racing fun stats: weekly and monthly leaders, driver activity, podiums, clean racing and popular cars.'));}
 return {funView,funContent};
}
