export const pages = [
  { path: "index.html", dictionary: "app.js", key: "home",
    en: { title: "ASG Racing — ACC Races, Championships & Community", description: "Explore Assetto Corsa Competizione races, championships, clubs and teams. Join the ASG Racing community and follow driver results and ratings.", heading: "Race with the ASG Racing community", text: "ASG Racing brings together Assetto Corsa Competizione drivers through public servers, scheduled races, championships, clubs and teams. Find a race, learn how to participate and follow your progress in the driver standings." },
    ru: { title: "ASG Racing — гонки ACC, чемпионаты и сообщество", description: "Сообщество Assetto Corsa Competizione: гонки, чемпионаты, клубы и команды, результаты и рейтинги пилотов. Узнайте, как участвовать в ASG Racing.", heading: "Гоняйте вместе с сообществом ASG Racing", text: "ASG Racing объединяет пилотов Assetto Corsa Competizione: публичные серверы, гонки по расписанию, чемпионаты, клубы и команды. Выберите гонку, узнайте, как участвовать, и следите за своим прогрессом в рейтинге пилотов." } },
  { path: "hourly/index.html", dictionary: "hourly/app.js", key: "hourly",
    en: { title: "ACC Race Schedule & Events | ASG Racing", description: "Find scheduled ACC races at ASG Racing. Check the track, start time, entry requirements and race format, then follow the results.", heading: "Scheduled ACC races", text: "Choose an upcoming Assetto Corsa Competizione race. Open its details to check the start time and time zone, track, eligible cars and participation requirements. The live schedule and results appear below." },
    ru: { title: "Расписание гонок ACC и события | ASG Racing", description: "Гонки ACC по расписанию в ASG Racing: трассы, время старта, допуск и формат. Выберите событие, ознакомьтесь с условиями участия и результатами.", heading: "Гонки ACC по расписанию", text: "Выберите ближайшую гонку Assetto Corsa Competizione. Откройте её подробности: время старта и часовой пояс, трассу, допустимые машины и условия участия. Актуальное расписание и результаты загружаются ниже." } },
  { path: "hourly/championship/index.html", dictionary: "hourly/championship/app.js", key: "championship",
    en: { title: "ACC Championship & Standings | ASG Racing", description: "Follow the ASG Racing ACC championship: upcoming rounds, race results and standings. Check each event's rules before joining.", heading: "ASG Racing ACC championship", text: "Follow championship progress, upcoming rounds and race results. Check the rules and entry requirements of the selected event before taking part; the current standings are loaded below." },
    ru: { title: "Чемпионат ACC и турнирная таблица | ASG Racing", description: "Чемпионат ACC в ASG Racing: ближайшие этапы, результаты гонок и турнирная таблица. Ознакомьтесь с правилами события перед участием.", heading: "Чемпионат ACC в ASG Racing", text: "Следите за ходом чемпионата, ближайшими этапами и результатами гонок. Перед участием изучите правила и условия допуска выбранного события. Актуальный зачёт загружается ниже." } },
  { path: "teams/index.html", dictionary: "src/pages/clubs-teams/catalog-page.js", key: "teams",
    en: { title: "ACC Clubs & Teams | ASG Racing", description: "Explore ASG Racing clubs and teams, public rosters and standings. Open a profile to learn more about the community and membership.", heading: "Find your racing community", text: "Meet the clubs and teams racing on ASG Racing servers. Open a public profile to see its description, roster and results, and check the available membership options. Recruitment depends on each club or team." },
    ru: { title: "Клубы и команды ACC | ASG Racing", description: "Клубы и команды ASG Racing: публичные составы, результаты и рейтинги. Изучите профиль сообщества и доступные варианты вступления.", heading: "Найдите своё гоночное сообщество", text: "Познакомьтесь с клубами и командами, выступающими на серверах ASG Racing. В публичном профиле доступны описание, состав, результаты и варианты вступления. Условия набора зависят от конкретного клуба или команды." } },
  { path: "community/index.html", dictionary: "app.js", key: "community",
    en: { title: "ACC Community & Race Stories | ASG Racing", description: "Meet the ASG Racing ACC community through race stories, photos and highlights. Find out how to join races and connect with other drivers.", heading: "A community beyond the finish line", text: "Share the experience of racing in Assetto Corsa Competizione: event stories, photos and memorable moments. Discover ASG Racing, meet other drivers and find your next race." },
    ru: { title: "Сообщество ACC и истории гонок | ASG Racing", description: "Сообщество ASG Racing в ACC: истории гонок, фотографии и яркие моменты. Узнайте, как участвовать и общаться с другими пилотами.", heading: "Сообщество за пределами финишной черты", text: "Общение и впечатления от гонок в Assetto Corsa Competizione: истории событий, фотографии и яркие моменты. Познакомьтесь с ASG Racing, найдите других пилотов и выберите следующий старт." } }
];
